# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:15.0.6
  amd64: ghcr.io/hassio-addons/base:15.0.6
  armv7: ghcr.io/hassio-addons/base:15.0.6
labels:
  org.opencontainers.image.title: "Pentair Home Addon"
  org.opencontainers.image.description: "An unofficial way to get Pentair Home data into Home Assistant"
  org.opencontainers.image.source: "https://github.com/ThomasLomas/ha-pentairhome-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
