---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Pentair Home
version: dev
slug: pentairhome
description: An unofficial way to get Pentair Home data into Home Assistant
url: https://github.com/ThomasLomas/ha-pentairhome-addon
arch:
  - aarch64
  - amd64
  - armv7
init: false
apparmor: true
services:
  - mqtt:need
options:
  pentairhome_username: ""
  pentairhome_password: ""
map:
  - addon_config:rw
schema:
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_user: "str?"
  mqtt_password: "str?"
  pentairhome_username: "str"
  pentairhome_password: "str"
