# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Pentair Home
version: "1.0.0"
slug: pentairhome
description: An unofficial way to get Pentair Home data into Home Assistant
url: https://github.com/ThomasLomas/ha-pentairhome-addon
arch:
  - aarch64
  - amd64
init: false
apparmor: false
services:
  - mqtt:need
options:
  mqtt_host: "127.0.0.1"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  pentairhome_username: ""
  pentairhome_password: ""
map:
  - config:rw
schema:
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_user: "str?"
  mqtt_password: "str?"
  pentairhome_username: "str"
  pentairhome_password: "str"
